# Generated by Django 5.1.6 on 2025-02-06 23:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeesDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='employee_image')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('d_o_b', models.DateField()),
                ('date_of_joining', models.DateField()),
                ('blood_group', models.CharField(max_length=3)),
                ('Aadhaar_no', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'Aadhaar number must be exactly 12 digits.')])),
            ],
        ),
    ]
